name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
    - uses: actions/checkout@v6
    - run: |
        sudo apt update
        sudo apt install -y 7zip bison build-essential flex git gnutls-dev python3-dev python3-pyelftools swig
        # Fixes armbian builder's "Failed to update binfmts" issue
        # https://forum.armbian.com/topic/52127-running-armbian-build-on-x86-64/
        sudo apt install -y qemu-user-static
        # For u-boot (armbian is built in a docker container)
        sudo apt install -y gcc-aarch64-linux-gnu
    - run: make img
    - run: |
        df -h
        ls -lh
      if: always()
    - run: |
        sudo apt install -y tree
        tree --du >tree.txt
    - name: Upload tree
      uses: actions/upload-artifact@v6
      with:
        name: tree
        path: tree.txt
    - run: git -C rk3528-tvbox log -n 1
    - run: git -C rk3528-tvbox diff HEAD
    - run: git -C rk3528-tvbox/armbian-build log -n 1
    - run: git -C rk3528-tvbox/armbian-build diff HEAD
    - run: git -C u-boot log -n 1
    - run: git -C u-boot diff HEAD
    - name: Upload u-boot images
      uses: actions/upload-artifact@v6
      if: always()
      with:
        name: dq08-u-boot
        path: |
          u-boot/idbloader.img
          u-boot/u-boot.itb
    - name: Upload dq08 u-boot+armbian image
      uses: actions/upload-artifact@v6
      if: always()
      with:
        name: dq08-uboot-armbian-image
        path: rk3528-tvbox/dq08.img
    # These files won't be needed any longer
    - name: Clean disk
      run: |
        df -h
        sudo rm -rf rk3528-tvbox/armbian-build
        df -h
        docker system prune -af --volumes || sudo docker system prune -af --volumes
        df -h
    - run: make zip
    - name: Upload recovery image
      uses: actions/upload-artifact@v6
      if: always()
      with:
        name: dq08-recovery-image
        path: dq08_recovery_*.zip
    - name: Upload ha-supervised images
      uses: actions/upload-artifact@v6
      if: always()
      with:
        name: dq08-ha-supervised-images
        path: dq08_ha_supervised_*.zip
